### ISSUE TITLE
Update (AttributeError: module 'ollama' has no attribute 'chat')

### ISSUE THREAD

**Issue by Sahil-Bhoite** [sunny2309/streamlit_chatbot#1]
The error is an AttributeError, indicating that the module you're using (ollama) does not have an attribute named chat. This suggests that the chat function or method you're trying to use is not available in the ollama module.

The traceback provides information about where the error occurred in your code. It points to the line where you're trying to call the chat function from the ollama module.

To resolve this issue, you should check the documentation or source code of the ollama module to verify if it provides a chat function or method. If not, you may need to use a different approach or module to implement the desired chatbot functionality in your Streamlit app.

**Comment by sunny2309** [comment]
I hope that you have installed this "ollama" python library. It has "chat()" function.  

https://pypi.org/project/ollama/

There is another "ollama-python" library. It does not have that method. Installing correct Python library should resolve issue.
